/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4b0938a9-64c3-42f9-b757-a32bed991842",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iRxp8DLtY",
    "aws_user_pools_web_client_id": "285hqe5100q5gg9f75p6raeja6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vvrmr6k6nffr7hr5vfwnkcvvve.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fh5ebizxjngzzlfgx5c3nw5c7y"
};


export default awsmobile;
